language: python
python:
  - "3.6"
install:
  - pip install pipenv
  - pipenv install --dev
script:
  - pipenv run pycodestyle .
  - pipenv run pydocstyle .
  - pipenv run mypy .
before_deploy:
  - pipenv lock -r > requirements.txt
  - touch requirements.txt
  - pip install -r requirements.txt -t .
  - zip -r deploy.zip *
deploy:
  provider: lambda
  function_name: "cscoffeechat"
  region: "us-west-2"
  role: "arn:aws:iam::655312369610:role/service-role/cscoffeechat"
  runtime: "python3.6"
  handler_name: "handler"
  zip: deploy.zip
  on:
    repo: daphliu/cscoffeechat
    branch: master
